openapi: 3.0.1
info:
  title: Physician Search API
  description: API for searching physician data by name.
  version: "1.0.0"
paths:
  /searchPhysician:
    get:
      summary: Search for a physician
      parameters:
        - name: name
          in: query
          required: true
          description: Name of the physician
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  specialty:
                    type: string
                  location:
                    type: string
        '400':
          description: Bad request
        '500':
          description: Internal server error
